### ISSUE TITLE
session is saved on global level instead of flow level

### ISSUE THREAD

**Issue by aderici** [rmbrich/node-red-contrib-wdio#10]
This makes it impossible to work with multiple sessions and run parallel tests.

I believe it is not even necessary to store the session somewhere other than the msg object itself like msg.session

Am i missing something?

**Comment by fightforlife** [comment]
Same issue here.
In the description it is stated, that it is based on flow level.

Is there anyway to change this?

**Comment by rmbrich** [comment]
Fixed in version 1.3.1. Session is now saved at the flow level.
